version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./database/volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doctor-assistant-app
