version: '3.9'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - doctor-assistant-app-network

  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - 'postgres'
    networks:
      - doctor-assistant-app-network

networks:
  doctor-assistant-app-network:
