version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./database/volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doctor-assistant-app
